image:
  repository: ghcr.io/ORG/llmapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: "1"
    memory: "1Gi"

securityContext:
  runAsNonRoot: true
  readOnlyRootFilesystem: true
